```yaml
title: 0xBGBGBG
description: Offensive Security | Pentest | Writeups

theme: just-the-docs

color_scheme: dark

url: https://0xBGBGBG.github.io

search_enabled: true

heading_anchors: true

back_to_top: true
back_to_top_text: "Voltar ao topo"

footer_content: "0xBGBGBG - Offensive Security Portfolio"
```
