title: 0xBGBGBG
description: Offensive Security | Pentest | Writeups

remote_theme: just-the-docs/just-the-docs

color_scheme: dark

url: https://0xBGBGBG.github.io

plugins:
  - jekyll-remote-theme

search_enabled: true
heading_anchors: true

back_to_top: true
back_to_top_text: "Voltar ao topo"

footer_content: "0xBGBGBG - Offensive Security Portfolio"

gh_edit_link: false

aux_links: {}

